export const mockPlayerProperties = [
    {
        prezzoCorrente: "100$",
        idGiocatore: "chi lo sa",
        numCasa: "0 per ora",
        prezzoCasaCorrente: "un botto",
        nome: "Viale dei Guardoni",
        colore: "Azzurro",
        affitto: "na cifra",
        ipoteca: "pochissimo Ovviamente",
        affitto1Casa: "na cifra*2",
        affitto2Case: "na cifra*3",
        affitto3Case: "na cifra*4",
        affitto4Case: "na cifra*5",
        affittoAlbergo: "na cifra*6",
    },
    {
        prezzoCorrente: "100$",
        idGiocatore: "chi lo sa",
        numCasa: "0 per ora",
        prezzoCasaCorrente: "un botto",
        nome: "Viale dei Guardoni",
        colore: "Verde",
        affitto: "na cifra",
        ipoteca: "pochissimo Ovviamente",
        affitto1Casa: "na cifra*2",
        affitto2Case: "na cifra*3",
        affitto3Case: "na cifra*4",
        affitto4Case: "na cifra*5",
        affittoAlbergo: "na cifra*6",
    },
    {
        prezzoCorrente: "100$",
        idGiocatore: "chi lo sa",
        numCasa: "0 per ora",
        prezzoCasaCorrente: "un botto",
        nome: "Bastoni Gran Difensore",
        colore: "Blu",
        affitto: "na cifra",
        ipoteca: "pochissimo Ovviamente",
        affitto1Casa: "na cifra*2",
        affitto2Case: "na cifra*3",
        affitto3Case: "na cifra*4",
        affitto4Case: "na cifra*5",
        affittoAlbergo: "na cifra*6",
    },
    {
        prezzoCorrente: "100$",
        idGiocatore: "chi lo sa",
        numCasa: "0 per ora",
        prezzoCasaCorrente: "un botto",
        nome: "Via Giustiniana",
        colore: "Blu",
        affitto: "na cifra",
        ipoteca: "pochissimo Ovviamente",
        affitto1Casa: "na cifra*2",
        affitto2Case: "na cifra*3",
        affitto3Case: "na cifra*4",
        affitto4Case: "na cifra*5",
        affittoAlbergo: "na cifra*6",
    },
    {
        prezzoCorrente: "100$",
        idGiocatore: "chi lo sa",
        numCasa: "0 per ora",
        prezzoCasaCorrente: "un botto",
        nome: "Er Colosseo",
        colore: "Azzurro",
        affitto: "na cifra",
        ipoteca: "pochissimo Ovviamente",
        affitto1Casa: "na cifra*2",
        affitto2Case: "na cifra*3",
        affitto3Case: "na cifra*4",
        affitto4Case: "na cifra*5",
        affittoAlbergo: "na cifra*6",
    },
    {
        prezzoCorrente: "100$",
        idGiocatore: "chi lo sa",
        numCasa: "0 per ora",
        prezzoCasaCorrente: "un botto",
        nome: "Antonello Venditti",
        colore: "Azzurro",
        affitto: "na cifra",
        ipoteca: "pochissimo Ovviamente",
        affitto1Casa: "na cifra*2",
        affitto2Case: "na cifra*3",
        affitto3Case: "na cifra*4",
        affitto4Case: "na cifra*5",
        affittoAlbergo: "na cifra*6",
    },


];
