export const NyThemeData = new Map();

NyThemeData.set(1, { name: "<- Via" });
NyThemeData.set(2, { name: "Vicolo Corto" });
NyThemeData.set(4, { name: "Vicolo Stretto" });
NyThemeData.set(5, { name: "Tassa Patrimoniale" });
NyThemeData.set(6, { name: "Stazione Sud" });
NyThemeData.set(7, { name: "Bastoni Gran Sasso" });
NyThemeData.set(9, { name: "Viale MonteRosa" });
NyThemeData.set(10, { name: "Viale Vesuvio" });
NyThemeData.set(12, { name: "Via Accademia" });
NyThemeData.set(14, { name: "Corso Ateneo" });
NyThemeData.set(15, { name: "Piazza Università" });
NyThemeData.set(16, { name: "Stazione Ovest" });
NyThemeData.set(17, { name: "Via Verdi" });
NyThemeData.set(18, { name: "Società Ferroviaria", icon: "subway" });
NyThemeData.set(19, { name: "Corso Raffaello" });
NyThemeData.set(20, { name: "Piazza Dante" });
NyThemeData.set(22, { name: "Via Marco Polo" });
NyThemeData.set(24, { name: "Corso Magellano" });
NyThemeData.set(25, { name: "Largo Colombo" });
NyThemeData.set(26, { name: "Stazione Nord" });
NyThemeData.set(27, { name: "Viale Costantino" });
NyThemeData.set(29, { name: "Viale Tirano" });
NyThemeData.set(30, { name: "Piazza Giulio Cesare" });
NyThemeData.set(32, { name: "Via Roma" });
NyThemeData.set(34, { name: "Corso Impero" });
NyThemeData.set(35, { name: "Largo Augusto" });
NyThemeData.set(36, { name: "Stazione Est" });
NyThemeData.set(37, { name: "Società Elettrica" });
NyThemeData.set(38, { name: "Viale Dei Giardini" });
NyThemeData.set(39, { name: "Tassa Patrimoniale" });
NyThemeData.set(40, { name: "Parco Della Vittoria" });

export default NyThemeData;