# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

# Questo workflow viene eseguito su push o pull request nel branch 'gitAction'.
on:
  push:
    branches: [gitAction]
  pull_request:
    branches: [gitAction]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Controlla il codice dal repository GitHub
      - uses: actions/checkout@v4

      # Configura JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # Usa la distribuzione Temurin
          cache: maven # Abilita il caching delle dipendenze Maven

      # Costruisce il progetto usando Maven
      - name: Build with Maven
        working-directory: NewMonopolyBackEnd # Specifica la directory contenente il pom.xml
        run: mvn -B package --file pom.xml # Opzione -B per modalità batch (senza input)

      # Sposta il working directory e aggiorna il grafo delle dipendenze
      - name: Update dependency graph
        run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph -DgraphFormat=json
        working-directory: NewMonopolyBackEnd
